spring:
  profiles:
    active: test
---
spring:
  profiles: development
  redis:
    host: 192.168.99.100
    port: 6379
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/dev?useSSL=false
    username: root
    password: dbpass
    initialize: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: test
  jpa:
    database: H2
  datasource:
    initialize: false
