spring:
  profiles:
    active: test
  application:
    name: online-store-web
---
spring:
  profiles: test
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/